title: Stoned 0.1 - Psychic Rocks
logo: /assets/img/stoned-logo.gif
description: Stoned is an IRL/URL project by Metaleptic and Miracle about the multiple mysterious corellations between stones and stonedness.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
